Inital commit
 ! [rejected]        main -> main (non-fast-forward)
 error: failed to push some refs to
 'https://github.com/HossVer/dropout-dashboard-detection-streamlit.git'
 hint: Updates were rejected because the tip of your current branch is
 behind
 hint: its remote counterpart. If you want to integrate the remote
 changes,
 hint: use 'git pull' before pushing again.
 hint: See the 'Note about fast-forwards' in 'git push --help' for
 details.

 o https://github.com/HossVer/dropout-dashboard-detection-streamlit.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/HossVer/dropout-dashboard-detection-streamlit.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.